### ISSUE TITLE
everything working okay other than smoke grenade 

### ISSUE THREAD

**Issue by DopeLovingHippy** [Mustachedom/md-houserobberies#11]
hello i try to use the smoke grenade and it goes through the actions but no smoke is generated would you possibly have any idea how i can fix this 

thanks

**Comment by Mustachedom** [comment]
Just noticed the error, I recently moved the shells a 100 vectors further down to avoid light flickering and I missed changing the smoke! 

Just fixed it in the client.lua

**Comment by DopeLovingHippy** [comment]
that fixed it for me mate but now sadly not showing for the robber .... not sure if thats how its mean't to work or if its just for the police after the robbery

**Comment by Mustachedom** [comment]
so you only get the option to target it as a cop, but if you want to make it so anyone could there will be a line that says 

```
 canInteract = function()
                        if Config.Houses[k]['spawned'] and  QBCore.Functions.GetPlayerData().job.type == 'leo' then return true end
                end
```

and you can just change it to 
```
 canInteract = function()
                        if Config.Houses[k]['spawned']  then return true end
                end
```

**Comment by DopeLovingHippy** [comment]
sorry i mean't if you smoke greanade while the robber is inside they don't see the smoke but the police do

**Comment by Mustachedom** [comment]
fixed in newest
