### ISSUE TITLE
Fall through map

### ISSUE THREAD

**Issue by Cyni4l** [Mustachedom/md-houserobberies#12]
I have the same issue as Rx3aya from the cfx forum post. When I break into any house, the inside coords are slightly off and I fall through the map. Tried to edit the insidecoords but still fall through the map. The k4mb1 free shells are installed but the teleport point seems to be just slightly off. This applies to every tier.

Other than that, works well. Would love to get it working.

Appreciate the release!

**Comment by Cyni4l** [comment]
Update to this - updating qb-interior fixed this issue.  Thanks again for an awesome script.

**Comment by sabotage93thctv** [comment]
same iisue tryed the same but didnt fix it :L also running debug but its not showing anything lol
