### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by ScaryWolfies** [Mustachedom/md-houserobberies#13]
hello, very good script but i have a issue and i dont know how to solve it, could you help me with this error ?
thank you.
also the smoke isnt working.
![image](https://github.com/user-attachments/assets/9157f31d-35e3-42ca-8a85-a96aede9033c)

**Comment by SKITTLE6969** [comment]
> hello, very good script but i have a issue and i dont know how to solve it, could you help me with this error ? thank you. also the smoke isnt working. ![image](https://private-user-images.githubusercontent.com/174193961/351741897-9157f31d-35e3-42ca-8a85-a96aede9033c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDg4OTUsIm5iZiI6MTcyMjUwODU5NSwicGF0aCI6Ii8xNzQxOTM5NjEvMzUxNzQxODk3LTkxNTdmMzFkLTM1ZTMtNDJjYS04YTg1LWE5NmFlZGU5MDMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMDM2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjUxNThmM2ViNzU1M2VlMjZjMDQ0M2ZkZDNiMDUxNGFiZjY1N2NiZjQ3YjFmZmUwOGQ1OTk3YmVlM2MxNWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tE2nWPQ87STFkkB6Pc_ZY7K3sATJ7w2IR0EOWUSeAHk)

error msg clearly says what the problem is :D

**Comment by ScaryWolfies** [comment]
> > hello, very good script but i have a issue and i dont know how to solve it, could you help me with this error ? thank you. also the smoke isnt working. ![image](https://private-user-images.githubusercontent.com/174193961/351741897-9157f31d-35e3-42ca-8a85-a96aede9033c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDg4OTUsIm5iZiI6MTcyMjUwODU5NSwicGF0aCI6Ii8xNzQxOTM5NjEvMzUxNzQxODk3LTkxNTdmMzFkLTM1ZTMtNDJjYS04YTg1LWE5NmFlZGU5MDMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMDM2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjUxNThmM2ViNzU1M2VlMjZjMDQ0M2ZkZDNiMDUxNGFiZjY1N2NiZjQ3YjFmZmUwOGQ1OTk3YmVlM2MxNWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tE2nWPQ87STFkkB6Pc_ZY7K3sATJ7w2IR0EOWUSeAHk)
> 
> error msg clearly says what the problem is :D

no shit sherlock, but i'm new in coding so idk what to do

**Comment by Mustachedom** [comment]
not my script
