### ISSUE TITLE
ps disptch error

### ISSUE THREAD

**Issue by sabotage93thctv** [Mustachedom/md-houserobberies#14]
![Screenshot 2024-09-11 073009](https://github.com/user-attachments/assets/aaf0717f-7dfd-453d-aadc-b5355d1133b2)

**Comment by CarlBishop** [comment]
you brole the config file of ps-dispatch. check for missing commas

**Comment by sabotage93thctv** [comment]
Ok I will do I may of found the issue but I’m confused as it’s a line that relates to config when I’m home I’ll post it :)
Sent from my iPhone

On 11 Sep 2024, at 13:17, CarlBishop ***@***.***> wrote:

﻿

you brole the config file of ps-dispatch. check for missing commas

**Comment by sabotage93thctv** [comment]
![Screenshot 2024-09-11 215833](https://github.com/user-attachments/assets/d384f506-bcfb-41e2-84e6-e1419d78167a)

trying to figure out if i should change it to register server even as this is where the error was :)

**Comment by sabotage93thctv** [comment]
![Screenshot 2024-09-11 220022](https://github.com/user-attachments/assets/10e647ec-9a4e-4361-bf8d-310dde2c6fee)


evenm if we do change it errors asks to change the parameter and changes back again to the original

**Comment by sabotage93thctv** [comment]
> you brole the config file of ps-dispatch. check for missing commas

ANY IDEAS BUD AS ITS GOT ME A BIT STUCK ATM LOL

**Comment by sabotage93thctv** [comment]
enev just looked at a fresh and latest download config is the same lol

**Comment by sabotage93thctv** [comment]
any help bud as clearly its nothing that we have done to ps dispatch as the luas are exact matches

**Comment by Mustachedom** [comment]
It's something you edited

This is an export issue not a house robbery issue. You have an error in the config of ps dispatch

**Comment by sabotage93thctv** [comment]
NO ITS NOT NOT FUNNY I DROPPED A NEW LUA IN FROM PS DISPATCH SAME ERROR ITS CAUSED BY THESE HOUSE ROBBERIES THERE IS NO ERROR IN THE CONFIG AS CAN BE SEEN NOT BEING RUDE

**Comment by Mustachedom** [comment]
ok and you dont need to yell because YOU broke something. Look at the error you have sent

you have a nil value called Config in PS-DISPATCH

that means your config is broken. It is not caused by these house robberies because it works on my many many qb builds, countless other cities that use this script. 

all my script does with ps-dispatch is simple. It uses an export. 

## as long as ps-dispatch is working, my script will work

**Comment by Mustachedom** [comment]
i never said it was funny, never reacted with a laughing face. You are acting like a child. Track down your error and have a nice day

**Comment by sabotage93thctv** [comment]
typical dev even when shown the luaS ARE THE SAME AS THE NEWEST UPDATE NO CHANGES

**Comment by sabotage93thctv** [comment]
AND BTW I MESSAGED BACK ON MY PHONE ITS CALLED AUTOCORRECT BUT WITH A ATTITUDE LIKE THAT ALL I CAN SAY IS OTHERS ARE HAVING THE SAME ISSUE IT CAN BE SEEN ON THESE TICKETS SO WHY CLEARLY LIE OTHERS ARE DROPPING OUT THE HOUSE ROBBERIES ECT ALL THE SAME BUGS
