### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Muzorm** [Mustachedom/md-houserobberies#7]
I installed the script without touching it and I get this error. Can you help me

"resource md-houserobberies: @md-houserobberies/client/main.lua:382: ‘end’ expected (to close ‘function’ at line 379) near "

no edits made

![image](https://github.com/Mustachedom/md-houserobberies/assets/123986261/2555d240-bc7e-4a4b-beec-40f02ff5f31a)

**Comment by Mustachedom** [comment]
sorry just saw this! I fixed this a few hours after initial push of job.type so you probably downloaded at that time, should be working with newest :)
